/*!
  role-auth.js — FINAL FIXED VERSION (2025) — HARDENED
  Bulletproof role/year access using explicit page mapping
  (Now rejects localStorage tampering for year-specific pages)
*/

(function () {
  'use strict';

  /* ==========================================================
     FIREBASE CONFIG
  ========================================================== */
  const FIREBASE_CONFIG = {
    apiKey: "AIzaSyBXqFTnZqi1Uzo_4k1s-cZrm__eSrQQuV8",
    authDomain: "home-1e252.firebaseapp.com",
    projectId: "home-1e252",
    storageBucket: "home-1e252.firebasestorage.app",
    messagingSenderId: "702969034430",
    appId: "1:702969034430:web:47ff6e815f2017fc8f10ef"
  };

  /* PUBLIC PAGES */
  const PUBLIC_PAGES = [
    "index.html",
    "login.html",
    "offline.html",
    "about.html"
  ];

  /* ==========================================================
     PAGE ACCESS MAP (AUTOGENERATED FOR YEAR 1–6)
     EXACT matches → NO GUESSING
  ========================================================== */
  const PAGE_ACCESS = {};

  function addTeacherPages(year) {
    const y = String(year);

    PAGE_ACCESS[`year${y}-t.html`] = { role: "teacher", year };
    PAGE_ACCESS[`teacher-dashboard.html`] = { role: "teacher", year: null };

    PAGE_ACCESS[`year${y}-first-term-teacher-dashboard.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-second-term-teacher-dashboard.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-third-term-teacher-dashboard.html`] = { role: "teacher", year };

    PAGE_ACCESS[`year${y}-first-term-assessment.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-first-term-lesson-teacher.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-first-term-lesson-upload.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-first-term-lesson-view.html`] = { role: "teacher", year };

    PAGE_ACCESS[`year${y}-second-term-assessment.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-second-term-lesson-teacher.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-second-term-lesson-upload.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-second-term-lesson-view.html`] = { role: "teacher", year };

    PAGE_ACCESS[`year${y}-third-term-assessment.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-third-term-lesson-teacher.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-third-term-lesson-upload.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-third-term-lesson-view.html`] = { role: "teacher", year };

    PAGE_ACCESS[`y${y}-cbt-teacher.html`] = { role: "teacher", year };

    PAGE_ACCESS[`year${y}-first-term-theory.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-second-term-theory.html`] = { role: "teacher", year };
    PAGE_ACCESS[`year${y}-third-term-theory.html`] = { role: "teacher", year };

    PAGE_ACCESS[`y${y}-cbt-result.html`] = { role: "teacher", year };
  }

  function addStudentPages(year) {
    const y = String(year);

    PAGE_ACCESS[`student-dashboard.html`] = { role: "student", year: null };
    PAGE_ACCESS[`year${y}-s.html`] = { role: "student", year };

    PAGE_ACCESS[`year${y}-first-term-student-dashboard.html`] = { role: "student", year };
    PAGE_ACCESS[`year${y}-second-term-student-dashboard.html`] = { role: "student", year };
    PAGE_ACCESS[`year${y}-third-term-student-dashboard.html`] = { role: "student", year };

    PAGE_ACCESS[`y${y}-cbt-student.html`] = { role: "student", year };

    PAGE_ACCESS[`year${y}-first-term-theory-view.html`] = { role: "student", year };
    PAGE_ACCESS[`year${y}-first-term-lesson-view.html`] = { role: "student", year };

    PAGE_ACCESS[`year${y}-second-term-theory-view.html`] = { role: "student", year };
    PAGE_ACCESS[`year${y}-second-term-lesson-view.html`] = { role: "student", year };

    PAGE_ACCESS[`year${y}-third-term-theory-view.html`] = { role: "student", year };
    PAGE_ACCESS[`year${y}-third-term-lesson-view.html`] = { role: "student", year };
  }

  // Add years 1–6 automatically
  for (let y = 1; y <= 6; y++) {
    addTeacherPages(y);
    addStudentPages(y);
  }

  /* ==========================================================
     FIREBASE LOADING
  ========================================================== */
  function loadScript(src) {
    return new Promise((resolve, reject) => {
      const s = document.createElement("script");
      s.src = src;
      s.async = true;
      s.onload = resolve;
      s.onerror = reject;
      document.head.appendChild(s);
    });
  }

  async function ensureFirebaseCompat() {
    if (window.firebase && window.firebase.apps) return window.firebase;

    const base = "https://www.gstatic.com/firebasejs/9.16.0/";
    await loadScript(base + "firebase-app-compat.js");
    await loadScript(base + "firebase-auth-compat.js");
    await loadScript(base + "firebase-firestore-compat.js");
    return window.firebase;
  }

  function initFirebase(firebase) {
    if (!firebase.apps.length) {
      firebase.initializeApp(FIREBASE_CONFIG);
    }
    return firebase;
  }

  /* ==========================================================
     USER FETCH: prefer secure Firebase-based identity
     — for year-specific pages we require a Firebase-validated user
     — localStorage fallback allowed only for non-year dashboards (role-only)
  ========================================================== */

  async function getUserFromFirebase(firebase) {
    return new Promise((resolve) => {
      firebase.auth().onAuthStateChanged(async (fbUser) => {
        if (!fbUser) return resolve(null);

        // 1) try token claims (fast & authoritative)
        try {
          const token = await fbUser.getIdTokenResult(true);
          const claims = token && token.claims ? token.claims : {};
          const role = claims.role || claims.user_role || claims.userRole || null;
          const year = claims.year || claims.user_year || claims.userYear || null;
          if (role) {
            return resolve({ uid: fbUser.uid, role: String(role).toLowerCase(), year: year ? Number(year) : null, source: 'claims' });
          }
        } catch (e) {
          // ignore and continue to Firestore fallback
        }

        // 2) Firestore fallback (reads trusted server data)
        try {
          if (firebase.firestore) {
            const db = firebase.firestore();
            const snap = await db.collection('users').where('uid', '==', fbUser.uid).limit(1).get();
            if (!snap.empty) {
              const d = snap.docs[0].data();
              if (d && d.role) {
                return resolve({ uid: fbUser.uid, role: String(d.role).toLowerCase(), year: d.year ? Number(d.year) : null, source: 'firestore' });
              }
            }
          }
        } catch (e) {
          // ignore
        }

        // 3) providerData / fallback (not trusted but last resort)
        try {
          const pd = fbUser.providerData && fbUser.providerData[0] ? fbUser.providerData[0] : {};
          if (pd && pd.role) return resolve({ uid: fbUser.uid, role: String(pd.role).toLowerCase(), year: pd.year ? Number(pd.year) : null, source: 'providerData' });
        } catch (e) { }

        // nothing found, still authenticated but no role info
        resolve({ uid: fbUser.uid, role: null, year: null, source: 'firebase_no_role' });
      }, (err) => {
        console.error('Auth state error:', err);
        resolve(null);
      });
    });
  }

  // STRICT local read: used only for non-year dashboards (role-only)
  function readLocalUserStrict() {
    try {
      const raw = localStorage.getItem("roleAuthUser");
      if (!raw) return null;
      const u = JSON.parse(raw);
      if (!u || !u.role) return null;
      return { uid: u.uid || null, role: String(u.role).toLowerCase(), year: u.year ? Number(u.year) : null, source: 'local' };
    } catch {
      return null;
    }
  }

  function redirect(reason) {
    const url = new URL("login.html", location.origin);
    url.searchParams.set("reason", reason);
    url.searchParams.set("redirect", location.pathname);
    location.replace(url.toString());
  }

  /* ==========================================================
     MAIN CHECK
  ========================================================== */

  (async function main() {
    const filename = location.pathname.split("/").pop();

    // allow public pages
    if (PUBLIC_PAGES.includes(filename)) return;

    const pageAccess = PAGE_ACCESS[filename];

    if (!pageAccess) {
      console.warn("No access rule for page:", filename);
      return redirect("unknown_page");
    }

    // Try to get a Firebase-validated user first
    let firebase = null;
    let user = null;
    try {
      firebase = await ensureFirebaseCompat();
      firebase = initFirebase(firebase);
      user = await getUserFromFirebase(firebase); // may be null
    } catch (e) {
      // ignore errors and try local fallback below
    }

    // If no firebase user AND the page is non-year dashboard (role-only), allow local fallback
    if (!user) {
      // If the page requires a YEAR (year-specific) we must NOT accept localStorage-only identities.
      if (pageAccess.year !== null) {
        // force authentication via login
        return redirect("not_authenticated_strict");
      }
      // pageAccess.year === null -> dashboard pages. allow strict local fallback as convenience.
      user = readLocalUserStrict();
    }

    if (!user) {
      return redirect("not_authenticated");
    }

    // Admin bypass (admins allowed anywhere)
    if (user.role === "admin") {
      window.__ROLE_AUTH = { user, allowed: true, pageAccess, filename };
      return;
    }

    // Role mismatch -> block
    if (pageAccess.role !== user.role) {
      return redirect("role_mismatch");
    }

    // Year mismatch -> block
    if (pageAccess.year !== null && pageAccess.year !== user.year) {
      return redirect("year_mismatch");
    }

    // Passed all checks
    window.__ROLE_AUTH = { user, allowed: true, pageAccess, filename };
    console.info("ROLE AUTH OK →", window.__ROLE_AUTH);
  })();

})();
